name: warehouse
services:
  hadoop-client:
    image: nph/spark-hadoop-client:latest
    container_name: hadoop-client
    ports:
      - 8080:8080
  hadoop-master-node:
    image: nph/spark-hadoop:latest
    container_name: hadoop-master-node
    environment:
      HDFS_NODE_TYPE: namenode
      YARN_NODE_TYPE: resourcemanager
  hadoop-worker-node-1:
    image: nph/spark-hadoop:latest
    container_name: hadoop-worker-node-1
    environment:
      HDFS_NODE_TYPE: datanode
      YARN_NODE_TYPE: nodemanager
  hadoop-worker-node-2:
    image: nph/spark-hadoop:latest
    container_name: hadoop-worker-node-2
    environment:
      HDFS_NODE_TYPE: datanode
      YARN_NODE_TYPE: nodemanager
  postgres:
    image: postgres:16.8
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 123456